Fix #2841: Update the documentation on oppia.github.io
oppia/oppia.github.io pull request #33
Opened 2017-03-06 09:13 UTC by terrameijar

Updated the pages/Screenshots.html page

2017-03-06 09:15 UTC, seanlip commented on pages/Screenshots.html
> +    Creator Dashboard
Do you still need this section? I think we can remove it altogether...

2017-03-06 09:15 UTC, seanlip requested changes
Thanks, just one comment, otherwise looks good!

2017-03-07 18:48 UTC, seanlip commented on pages/Screenshots.html
> +  <p><img src="static/images/library.png" alt="Screenshot of gallery page" class="screenshot-image"></p>
Alt text should be changed, too.

Are you planning to delete the old image? (Only do so if we don't use it elsewhere.)

2017-03-07 18:49 UTC, seanlip reviewed
Thanks! Sorry, saw just one more thing.

2017-03-09 23:01 UTC, terrameijar commented on pages/Screenshots.html
> +  <p><img src="static/images/library.png" alt="Screenshot of gallery page" class="screenshot-image"></p>
Yes I will delete the old image but not right now, it is in use in at least one other location so I will only delete it once I have updated the other page that contains this image.

2017-03-10 00:17 UTC, seanlip approved these changes

2017-03-10 00:18 UTC, seanlip commented
Sounds good, thanks! Merging.

(Also, please feel free to submit follow-up PRs to update other parts of the site. Thanks!)

2017-03-10 00:18 UTC, merged

2017-03-10 13:27 UTC, terrameijar commented
This was my first PR and I'm excited about getting it merged. I will get back to updating other parts of the site after I'm done doing cartwheels. Thank you!

2017-03-10 18:35 UTC, seanlip commented
Ah yes, I meant to congratulate you on your first PR, but forgot! Better late than never, though, so congratulations, and thanks :-)