Dev
oppia/oppia.github.io pull request #34
Opened 2017-03-23 00:54 UTC by terrameijar

Edits of the TheExplorationGallery.html page. I renamed this page to TheExplorationLibrary.html, changed all references to exploration gallery to library and rephrased some of the text.

2017-03-23 00:57 UTC, seanlip requested changes
This is great. Thank you for the changes! I have a few comments.

2017-03-23 00:57 UTC, seanlip commented on app.js
>      .when('/TheExplorationGallery', {
Should this be changed to /TheExplorationLibrary as well?

2017-03-23 00:57 UTC, seanlip commented on pages/TheExplorationLibrary.html
> +    do. Hover the cursor over the about menu in the navigation bar at the top right of the page to access the blog, join the discussion forum or learn how to get started.
Consider keeping lines to 80 chars or so, similar to the rest of the file -- it makes it a bit easier to read when reviewing.

Also, suggest: "about menu" --> "About menu"

2017-03-23 00:57 UTC, seanlip commented on pages/TheExplorationLibrary.html
> +  <img src="static/images/libraryCategoryHighlighted.png" width="100%">
Shouldn't this picture show the user selecting "Mathematics" from the category dropdown, rather than their typing "Mathematics" into the search bar?

2017-03-25 22:52 UTC, terrameijar commented on pages/TheExplorationLibrary.html
> +  <img src="static/images/libraryCategoryHighlighted.png" width="100%">
Right, I have edited the screenshot.

2017-03-25 22:54 UTC, seanlip approved these changes
LGTM. Thanks!

2017-03-25 22:54 UTC, merged