Updated screenshots to match current version of Oppia
oppia/oppia.github.io pull request #36
Opened 2017-04-03 21:20 UTC by terrameijar

I updated the screenshots in the key concepts page to match the current look of oppia.org. The first screenshot of the three balls I made is bigger than the second one so I adjusted its width attribute to 75% . I hope this is ok.

2017-04-03 21:46 UTC, seanlip requested changes
Thanks, @terrameijar! I see one issue: the threeBalls.png image seems to omit the bottom part of the first question and the student's answer. Can those be included? Otherwise we end up missing a bit in the middle.

Note that you can navigate back to the previous card after answering, by using the arrows at the top. (You don't really need to include those in the screenshot, btw.)

Also, for the second image, could you make both images look the same? In particular, include the progress dots in both or in neither, but not in just one.

Thanks!

2017-04-13 17:28 UTC, terrameijar commented
I have updated the images, please review

2017-04-13 19:47 UTC, seanlip approved these changes

2017-04-13 19:48 UTC, seanlip commented
Very nice, thanks @terrameijar!

2017-04-13 19:48 UTC, merged