Fixes #3610: Documentation for Hint Editor
oppia/oppia.github.io pull request #38
Opened 2017-07-06 16:33 UTC by kevintab95

I think the issue was submitted in the main oppia project rather than oppia.github.io . This PR documents the editor functionality for hints.

2017-07-10 06:15 UTC, seanlip requested changes

2017-07-10 06:15 UTC, seanlip commented on pages/TheExplorationEditor.html
> +      <li>The learner may request a hint if he/she got an answer wrong at-least
The learner submitted a wrong answer at least once.

2017-07-10 06:15 UTC, seanlip commented on pages/TheExplorationEditor.html
> +      <li>Or it has been more than 30 seconds since the learner has submitted an
It has been more than 30 seconds since the learner last submitted an answer.

2017-07-13 09:12 UTC, seanlip commented
@kevintab95 -- could you finish this please? Also it would be great if at least one of @tjiang11 @joshuacano @kevinlee12 could review this.

2017-07-13 22:56 UTC, tjiang11 requested changes

2017-07-13 22:56 UTC, tjiang11 commented on pages/TheExplorationEditor.html
> +    make use of when he/she is stuck. To prevent learners from abusing this
You can add a list of hints that the learner can use when stuck.

2017-07-15 13:46 UTC, tjiang11 approved these changes

2017-07-15 20:54 UTC, seanlip approved these changes

2017-07-15 20:54 UTC, merged