Updated `Create an exploration` page according to new UI changes.
oppia/oppia.github.io pull request #58
Opened 2022-01-11 10:20 UTC by sahiljoster32

Here is the proof of changes being correct:
![Screenshot from 2022-01-11 15-48-13](https://user-images.githubusercontent.com/12553576/148924826-41a59b21-91a8-468c-969d-c7b699bb1704.png)

2022-01-11 13:07 UTC, krishita30j requested changes
@sahiljoster32 can you rename the png filename from libraryCreateButton to creatorDashboardCreateButton? Thanks.

2022-01-11 13:19 UTC, sahiljoster32 commented
@krishita30j Done!

2022-01-11 14:13 UTC, krishita30j commented
@BenHenning PTAL! Thanks.

2022-01-13 16:33 UTC, krishita30j approved these changes

2022-01-13 16:34 UTC, krishita30j commented
@seanlip PTAL!

2022-01-13 17:31 UTC, seanlip requested changes
Thanks, just one comment.

Also one question -- when should this change be deployed to the live github.io site?

2022-01-13 17:31 UTC, seanlip commented on pages/CreatingAnExploration.html
> +  <img src="static/images/creatorDashboardCreateButton.png" style="width: 100%;" alt="A menu bar at the top of the page, containing the 'Create' option circled in yellow, which is positioned on the r
The alt text seems wrong?

2022-01-14 07:43 UTC, sahiljoster32 commented on pages/CreatingAnExploration.html
> +  <img src="static/images/creatorDashboardCreateButton.png" style="width: 100%;" alt="A menu bar at the top of the page, containing the 'Create' option circled in yellow, which is positioned on the r
Done!

2022-01-14 07:43 UTC, sahiljoster32 commented
@seanlip PTAL!

2022-01-14 07:46 UTC, seanlip commented
I can't yet -- I still need an answer to the top-level question.

2022-01-14 08:12 UTC, sahiljoster32 commented
Since, this site is deployed to the github pages. So, as soon as we update the main(oppia.github.io) repository, oppia.github.io site should updated accordingly.

2022-01-14 08:34 UTC, sahiljoster32 commented
@seanlip PTAL!

2022-01-14 08:45 UTC, seanlip commented
OK, thanks -- I think that seems fine, we can update it immediately.

I just checked the Oppia site though, and the Create Exploration button positioning is weird. Should it look like this?
![Screenshot from 2022-01-14 16-44-48](https://user-images.githubusercontent.com/10575562/149484578-24f69545-8b0d-4bd5-8afe-5230aebd74b8.png)

I would have thought that the button should be aligned with the top-right.

2022-01-14 08:53 UTC, sahiljoster32 commented
Since, some of the PR's are not deployed to oppia.org. 
as explaind by you in issue #14604
https://github.com/oppia/oppia/issues/14604
but now, in test server it is fixed.

https://user-images.githubusercontent.com/12553576/149486834-a8dd1074-5e83-4fde-9fff-0fe3eae19a91.mp4

2022-01-14 08:53 UTC, sahiljoster32 commented
@seanlip PTAL!

2022-01-14 15:59 UTC, seanlip approved these changes
OK, looks good, thanks!

2022-01-14 15:59 UTC, merged